on:
  pull_request:
    types:
      - closed
    branches: [develop, main]

jobs:
  build-prod:
    runs-on: ${{ needs.jobs.build.runs-on }}
    steps:
      - uses: actions/checkout@v3

      - name: Define version variable
        run: |
          if grep -q "major" $GITHUB_EVENT_PATH; then
            echo "version=major >> $GITHUB_OUTPUT"
          elif grep -q "minor" $GITHUB_EVENT_PATH; then
            echo "version=minor >> $GITHUB_OUTPUT"
          else
            echo "version=patch >> $GITHUB_OUTPUT"
          fi

      # - name: Get the start word in the pull request body
      #   run: |
      #     start_word=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body' | awk -F: '{print $1}')
      #     echo "START_WORD::$start_word >> $GITHUB_OUTPUT"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - run: echo ${{ secrets.ENV }}| base64 -d > .env

      - run: flutter --version
      - run: flutter pub get

      - run: echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > android/app/google-services.json
      - run: echo ${{ secrets.KEY_PROPERTIES }} | base64 -d > android/key.properties
      - run: echo ${{ secrets.KEYSTONE_JKS }} | base64 -d > android/app/keystone.jks

      - name: Download flutter dependency
        run: flutter pub get

      - name: bump flutter version
        run: flutter pub run cider bump ${{ outputs.version }} --bump-build

      - run: flutter build appbundle --release
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3
        with:
          name: ditonton-aja.abb
          path: build/app/outputs/bundle/release/app-release.aab

      - uses: actions/upload-artifact@v3
        with:
          name: ditonton-aja.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: get the current version
        # get the version after bump
        if: github.ref == 'ref/head/main'
        run: echo "version_number=$(flutter pub run cider version) >> $GITHUB_OUTPUT"

      - name: update CHANGELOG.md file
        if: github.ref == 'ref/head/main'
        run: |
          while read -r line; do
            flutter pub run cider log added $line
          done < <(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body')

          flutter pub run cider release --date=today

      - name: Update bump version
        if: github.ref == 'ref/head/main'

        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'github-boot@noreply.github.com'
          git add .
          git commit -m 'bump version to ${{ GITHUB_OUTPUT.version_number }}'
          git push

  deploy:
    runs-on: macos-latest
    needs: build-prod
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ditonton-aja.abb
      - name: Generate Service Account Json File
        run: echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 -d > android/app/service-account.json

      - name: Publish Android App with hight priority
        uses: r0adkll/upload-google-play@v1

        if: github.ref == 'ref/head/main' and contains(github.event.head_commit.message, 'hotfix')

        with:
          serviceAccountJson: android/app/service-account.json
          packageName: com.dicoding.ditonton
          releaseFiles: ${{ steps.download.outputs.download-path }}
          track: production
          inAppUpdatePriority: 5
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib

      - name: Publish Android App with normal priority
        uses: r0adkll/upload-google-play@v1

        if: github.ref == 'ref/head/main' and !contains(github.event.head_commit.message, 'hotfix')

        with:
          serviceAccountJson: android/app/service-account.json
          packageName: com.dicoding.ditonton
          releaseFiles: ${{ steps.download.outputs.download-path }}
          track: production
          inAppUpdatePriority: 3
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib

      - name: Publish Android App with normal priority
        uses: r0adkll/upload-google-play@v1

        if: github.ref == 'ref/head/develop'

        with:
          serviceAccountJson: android/app/service-account.json
          packageName: com.dicoding.ditonton
          releaseFiles: ${{ steps.download.outputs.download-path }}
          track: internal
          inAppUpdatePriority: 5
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib

  release:
    runs-on: macos-latest
    if: github.ref == 'ref/head/main'

    needs: build-prod

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact Abb bundle
        uses: actions/download-artifact@v3
        with:
          name: ditonton-aja.abb

      - name: Download Artifact Apk
        uses: actions/download-artifact@v3
        with:
          name: ditonton-aja.apk

      - name: Generate version
        id: generate-version
        uses: actions/create-version@v1

      - name: Create tag
        uses: actions/create-tag@v1
        with:
          tag: v${{ needs.build-prod.outputs.version_number }}
          ref: ${{ github.event.pull_request.merged_commit.sha }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build-prod.outputs.version_number }}
          release_name: Release v${{ needs.build-prod.outputs.version_number }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: svenstaro/upload-release-asset@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          file: build/app/outputs/*

          tag: v${{ needs.build-prod.outputs.version_number }}
          asset_name: Ditonton-aja-${{ needs.build-prod.outputs.version_number }}
          overwrite: true
          file_glob: true
